### ISSUE TITLE
Does not seem to generate well-formed ELF binaries

### ISSUE THREAD

**Issue by tekknolagi** [kragen/stoneknifeforth#2]
I'm running Ubuntu and when I run `./build`, I get a permission denied error upon `execve` -- which I take to mean that it cannot even attempt to execute binaries produced. Have ELF binaries changed much since 2008?

**Comment by tekknolagi** [comment]
Alright, so it turns out that yours generates *just fine* binaries but they either require sudo to execute on a 64-bit system or something like `qemu-i386`. My apologies. Incidentally, I've made a C++ port of stoneknifeforth that's of comparable length: https://github.com/tekknolagi/stoneknifecpp.

**Comment by larsbrinkhoff** [comment]
Hello @tekknolagi,

I made a pull request here to make GitHub detect the `.tbf1` files as Forth.  Would you consider this for your version as well?

**Comment by tekknolagi** [comment]
Are the syntaxes close enough that it makes sense? In any case, sure why
not.

Lars Brinkhoff <notifications@github.com> schrieb am Do., 20. Juli 2017,
09:38:

**Comment by larsbrinkhoff** [comment]
I think so.  Stoneknifeforth uses whitespace delimited tokens, starts new definitions with `:` and ends them with `;`.  That's the very basics of Forth syntax.

**Comment by tekknolagi** [comment]
Then by all means yes, submit away

Lars Brinkhoff <notifications@github.com> schrieb am Do., 20. Juli 2017,
09:51:

**Comment by kragen** [comment]
That's pretty interesting! I'm running LinuxMint on an amd64 CPU at the moment and it seems to be able to run StoneKnifeForth's i386 binaries even after I uninstall qemu-user. I do have a pretty extensive set of `*:i386` packages installed, as well as things like libc6-i386, but I'm not sure how that would help SKF, because the binaries it generates are all, so far, statically linked. I'm guessing there's some kind of kernel configuration parameter that governs whether the amd64 kernel supports running processes in i386 mode or not.

By the way, thanks a million for figuring out why it had been broken on modern Linuxes for years! The C++ interpreter looks cool, too.

**Comment by tekknolagi** [comment]
Is this related to https://news.ycombinator.com/item?id=5204255 ?
